version: "3.8"
services:
    front-end:
        image: cnr
        build: .
        ports:
            - "1234:1234"
            - "1235:1235"
        volumes:
            - ./src:/app/src
        environment:
            - DOCUMENT_MICROSERVICE_URL=http://localhost:3000
